config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'ideas#index'
  get 'static_pages/home', to: 'static_pages#home'
  get 'static_pages/about'

  get 'users/new'

  devise_for :users

  resources :ideas

  resources :users

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	attr_accessible :name, :description, :user_id

	validates :description, :length => { :maximum => 450 }
	
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :ideas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.user_id = current_user.id
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  	respond_to :html
  end
  
  def home
  	respond_to :html
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def edit
  end

  def show
  end

  def create
  	@user = User.new(user_params)
  	respond_to do |format|
  		if @user.save
  			format.html { redirect_to @user, notice: 'User was successfully created.' }
  			format.json { render :show, status: :created, location: @user }
  		else 
  			format.html { render :new }
  			format.json { render json: @user.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def destroy
  	@user.destroy 
  	respond_to do |format|
  		format.html { redirect_to users_url, notice: 'User was successfully deleted.' }
  		format.json { head :no_content }
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Alex App"
		if page_title.empty? 
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<%= simple_form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<div class="container">
  <div id="index-ideas">
    <div class="row">
      <div class="col-md-7">
        <input type="text" name="new-idea" placeholder="Add new idea here:">
        <%= link_to 'New Idea', new_idea_path %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-7">
        <% @ideas.each do |idea| %>
          <div class="user-idea">
            <h3><%= current_user.email %></h3>
            <h4><%= idea.name %></h4>
            <p class="idea-description"><%= idea.description %></p>
            <p><%= idea.picture %></p>
            <p class="idea-links">
              <%= link_to "Show", idea %>
              <%= link_to "Edit", edit_idea_path(idea) %>
              <%= link_to "Delete", idea, method: :delete, data: {
                confirm: "Are you sure?" } %>
            </p>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@idea.picture_url, :width => 400) if @idea.picture.present? %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  
	  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
	  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">

	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div id="wrap">
			<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="/">Alex app</a>
					</div>
					<div class="collapse navbar-collapse">
						<!--
						<ul class="nav navbar-nav">
							<li class="active"><a href="/ideas">Ideas</a></li>
						</ul>
						-->
						<p class="navbar-text pull-right">
							<% if user_signed_in? %>
								Logged in as <strong><%= current_user.email %></strong>.
								<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
								<%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
							<% else %>
								<%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link' %>
								<%= link_to 'Login', new_user_session_path, :class => 'navbar-link' %>
							<% end %>

					</div>
					</div>
			</nav>

			<%= yield %>

			<div id="footer">
				<div class="row">
					<div class="links-footer col-md-2">
						<%= link_to 'About me', static_pages_about_path, :class => 'about-me' %>
					</div>
					<div class="copyright col-md-2 col-md-offset-8">
						<p>2014 Alex Geogea</p>
					</div>
				</div>
			</div>

			<script src="//railsgirls.com/assets/bootstrap.js"></script>
		</div>
	</body>
</html>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>